from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field, StrictBool, FilePath
from langchain_core.vectorstores.base import VectorStoreRetriever

class HistoricalEvent(BaseModel):
    """Structured representation of a historical event returned by the MCP Server."""
    year: int = Field(description="Year in which the event occurred.")
    title: str = Field(description="Brief headline or summary of the fact.")
    page_name: str = Field(description="Title of the associated Wikipedia article.")
    category: str = Field(default="General History", description="Thematic category of the event.")

class EventList(BaseModel):
    events: list[HistoricalEvent] = Field(description="A list of historical events.")

class RankedSelection(BaseModel):
    """Result of curatorial and editorial analysis by the ranking agent."""
    selected_event: HistoricalEvent = Field(
        description="The historical event chosen as the most relevant and impactful."
    )
    gonzo_hook: str = Field(
        description="The chaotic, urgent or ironic angle under which the story will be narrated."
    )

class DetailedEvent(BaseModel):
    """Detailed information about a specific historical event."""
    title: str = Field(description="Title of the historical event.")
    source: str = Field(description="Source of the information about the event.")

class ChronoState(BaseModel):
    """Global shared state between all nodes in the LangGraph."""
    target_date: str = Field(
        default=datetime.now().strftime("%m/%d"),
        description="Target date in 'MM/DD' format"
    )
    raw_events: List[HistoricalEvent] = Field(
        default_factory=list,
        description="Raw payload returned by the MCP Server"
    )
    batched_events: EventList = Field(
        default=EventList(events=[]),
        description="Filtered payload returned by the LLM"
    )
    detailed_event: Optional[DetailedEvent] = Field(
        default=None,
        description="Detailed information about a specific historical event"
    )
    curated_story: Optional[RankedSelection] = Field(
        default=None,
        description="Selected event and editorial hook via Pydantic"
    )
    final_article: Optional[str] = Field(
        default=None,
        description="Final article name"
    )
    published_path: Optional[FilePath] = Field(
        default=None,
        description="Path to the article published"
    )
    photo_filename: Optional[str] = Field(
        default=None,
        description="Photo filename generated by the photographer node"
    )
    custom_event: Optional[HistoricalEvent] = Field(
        default=None,
        description="Custom event selected by the user for dispatch generation"
    )
    retriever: Optional[VectorStoreRetriever] = Field(
        default=None,
        description="Vector store for semantic search and retrieval"
    )
    error: StrictBool = Field(
        default=False,
        description="Whether or not to raise an error"
    )
    error_msg: Optional[str] = Field(
        default=None,
        description="Error message"
    )