from typing import List, Optional
from typing_extensions import TypedDict
from pydantic import BaseModel, Field


class HistoricalEvent(BaseModel):
    """Structured representation of a historical event returned by the MCP Server."""
    year: int = Field(description="Year in which the event occurred.")
    title: str = Field(description="Brief headline or summary of the fact.")
    description: str = Field(description="Details and informative extract about the occurrence.")
    category: str = Field(default="General History", description="Thematic category of the event.")


class RankedSelection(BaseModel):
    """Result of curatorial and editorial analysis by the ranking agent."""
    selected_event: HistoricalEvent = Field(
        description="The historical event chosen as the most relevant and impactful."
    )
    gonzo_hook: str = Field(
        description="The chaotic, urgent or ironic angle under which the story will be narrated."
    )
    suggested_modern_topic: str = Field(
        description="Contemporary topic suggested for correlating with the historical fact."
    )


class ChronoState(TypedDict):
    """Global shared state between all nodes in the LangGraph."""
    target_date: str                           # Target date in 'MM/DD' format
    raw_events: List[dict]                     # Raw payload returned by the MCP Server
    curated_story: Optional[RankedSelection]   # Selected event and editorial hook via Pydantic
    modern_context: Optional[str]              # Summary of correlation with current events
    final_article: Optional[str]               # Final Gonzo-style article drafted
    published_path: Optional[str]              # Path to the saved .md file on disk
    filename: Optional[str]                  # Photo filename generated by the photographer node
    custom_event: Optional[HistoricalEvent]                  # Custom event selected by the user for dispatch generation