from typing import List, Optional
from typing_extensions import TypedDict
from pydantic import BaseModel, Field
from langchain_core.vectorstores.base import VectorStoreRetriever

class HistoricalEvent(BaseModel):
    """Structured representation of a historical event returned by the MCP Server."""
    year: int = Field(description="Year in which the event occurred.")
    title: str = Field(description="Brief headline or summary of the fact.")
    page_name: str = Field(description="Title of the associated Wikipedia article.")
    category: str = Field(default="General History", description="Thematic category of the event.")
class EventList(BaseModel):
    events: list[HistoricalEvent] = Field(description="A list of historical events.")
class RankedSelection(BaseModel):
    """Result of curatorial and editorial analysis by the ranking agent."""
    selected_event: HistoricalEvent = Field(
        description="The historical event chosen as the most relevant and impactful."
    )
    gonzo_hook: str = Field(
        description="The chaotic, urgent or ironic angle under which the story will be narrated."
    )

class DetailedEvent(BaseModel):
    """Detailed information about a specific historical event."""
    title: str = Field(description="Title of the historical event.")
    source: str = Field(description="Source of the information about the event.")

class ChronoState(TypedDict):
    """Global shared state between all nodes in the LangGraph."""
    target_date: str                           # Target date in 'MM/DD' format
    raw_events: List[HistoricalEvent]          # Raw payload returned by the MCP Server
    batched_events: EventList                  # Filtered payload returned by the LLM
    detailed_event: Optional[DetailedEvent]    # Detailed information about a specific historical event
    curated_story: Optional[RankedSelection]   # Selected event and editorial hook via Pydantic
    final_article: Optional[str]               # Final Gonzo-style article drafted
    published_path: Optional[str]              # Path to the saved .md file on disk
    filename: Optional[str]                    # Photo filename generated by the photographer node
    custom_event: Optional[HistoricalEvent]    # Custom event selected by the user for dispatch generation
    retriever: Optional[VectorStoreRetriever]  # Vector store for semantic search and retrieval